model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic.claude-3-haiku-20240307-v1:0

  - model_name: claude-instant-v1
    litellm_params:
      model: anthropic.claude-instant-v1